{{- include "ffc-helm-library.deployment" (list . "ffc-digital-form-builder.deployment") -}}
{{- define "ffc-digital-form-builder.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-digital-form-builder.container") }}
{{- end -}}
